/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.webhook.model.impl;

import com.liferay.webhook.model.WebhookEntry;
import com.liferay.webhook.service.WebhookEntryLocalServiceUtil;

/**
 * The extended model base implementation for the WebhookEntry service. Represents a row in the &quot;WebhookEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WebhookEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WebhookEntryImpl
 * @see WebhookEntry
 * @generated
 */
public abstract class WebhookEntryBaseImpl
	extends WebhookEntryModelImpl implements WebhookEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a webhook entry model instance should use the <code>WebhookEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			WebhookEntryLocalServiceUtil.addWebhookEntry(this);
		}
		else {
			WebhookEntryLocalServiceUtil.updateWebhookEntry(this);
		}
	}

}