/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.shop.by.diagram.model.impl;

import com.liferay.commerce.shop.by.diagram.model.CPDefinitionDiagramPin;
import com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramPinLocalServiceUtil;

/**
 * The extended model base implementation for the CPDefinitionDiagramPin service. Represents a row in the &quot;CPDefinitionDiagramPin&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPDefinitionDiagramPinImpl}.
 * </p>
 *
 * @author Andrea Sbarra
 * @see CPDefinitionDiagramPinImpl
 * @see CPDefinitionDiagramPin
 * @generated
 */
public abstract class CPDefinitionDiagramPinBaseImpl
	extends CPDefinitionDiagramPinModelImpl implements CPDefinitionDiagramPin {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp definition diagram pin model instance should use the <code>CPDefinitionDiagramPin</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CPDefinitionDiagramPinLocalServiceUtil.addCPDefinitionDiagramPin(
				this);
		}
		else {
			CPDefinitionDiagramPinLocalServiceUtil.updateCPDefinitionDiagramPin(
				this);
		}
	}

}