#!/bin/bash

function check_usage {
	export CUSTOM_ELEMENT_NAME="liferay-hello-world-v2"
}

function create_files {
	remove_unnecessary_files
	write_index_js
	write_styles
}

function create_react_app {
	yarn create react-app ${1}
}

function get_temp_dir {
	echo hello-world-v2
}

function main {
	check_usage

	local temp_dir=$(get_temp_dir)

	create_react_app ${temp_dir}

	cp react-bundle-rename.sh ${temp_dir}

	cd ${temp_dir}

	echo "SKIP_PREFLIGHT_CHECK=true" > ".env"

	sed -i -e "s|<div id=\"root\"></div>|<$CUSTOM_ELEMENT_NAME></$CUSTOM_ELEMENT_NAME>|g" public/index.html

	yarn remove @testing-library/jest-dom @testing-library/react @testing-library/user-event web-vitals
	
	cd src
	
	create_files
}

function write_index_js {
cat <<EOF > index.js
import React from 'react';
import ReactDOM from 'react-dom';

import './styles/index.scss';

class WebComponent extends HTMLElement {
	connectedCallback() {
		ReactDOM.render(
			<div className="hello-world">
				<h1>Hello World</h1>
			</div>,
			this
		);
	}
}

const ELEMENT_ID = '${CUSTOM_ELEMENT_NAME}';

if (!customElements.get(ELEMENT_ID)) {
	customElements.define(ELEMENT_ID, WebComponent);
}
EOF
}

function write_styles {
	mkdir styles

	cat <<EOF > styles/variables.scss
\$primary-color: #295ccc;
EOF

	cat <<EOF > styles/index.scss
${CUSTOM_ELEMENT_NAME} {
	@import 'variables';
	@import 'hello-world.scss';
}
EOF

	cat <<EOF > styles/hello-world.scss
.hello-world {
	h1 {
		color: \$primary-color;
		font-weight: bold;
	}
}
EOF
}


function remove_unnecessary_files {
	#
	# All the files deleted here, are generated by Create React App
	#

	rm -f App* index* setupTests.js logo.svg reportWebVitals.js
	rm -f ../public/logo* ../public/manifest.json ../public/favicon.ico ../public/robots.txt
}

main