apiDir: "../headless-admin-address-api/src/main/java"
apiPackagePath: "com.liferay.headless.admin.address"
application:
    baseURI: "/headless-admin-address"
    className: "HeadlessAdminAddressApplication"
    name: "Liferay.Headless.Admin.Address"
author: "Drew Brokke"
clientDir: "../headless-admin-address-client/src/main/java"
forcePredictableOperationId: true
testDir: "../headless-admin-address-test/src/testIntegration/java"