/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.term.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommerceTerm service. Represents a row in the &quot;CommerceTerm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.term.model.impl.CommerceTermModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.term.model.impl.CommerceTermImpl</code>.
 * </p>
 *
 * @author Luca Pellizzon
 * @see CommerceTerm
 * @generated
 */
@ProviderType
public interface CommerceTermModel
	extends AuditedModel, BaseModel<CommerceTerm>, LocalizedModel, MVCCModel,
			ShardedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce term model instance should use the {@link CommerceTerm} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce term.
	 *
	 * @return the primary key of this commerce term
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce term.
	 *
	 * @param primaryKey the primary key of this commerce term
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this commerce term.
	 *
	 * @return the mvcc version of this commerce term
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this commerce term.
	 *
	 * @param mvccVersion the mvcc version of this commerce term
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the external reference code of this commerce term.
	 *
	 * @return the external reference code of this commerce term
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this commerce term.
	 *
	 * @param externalReferenceCode the external reference code of this commerce term
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the commerce term ID of this commerce term.
	 *
	 * @return the commerce term ID of this commerce term
	 */
	public long getCommerceTermId();

	/**
	 * Sets the commerce term ID of this commerce term.
	 *
	 * @param commerceTermId the commerce term ID of this commerce term
	 */
	public void setCommerceTermId(long commerceTermId);

	/**
	 * Returns the company ID of this commerce term.
	 *
	 * @return the company ID of this commerce term
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce term.
	 *
	 * @param companyId the company ID of this commerce term
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce term.
	 *
	 * @return the user ID of this commerce term
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce term.
	 *
	 * @param userId the user ID of this commerce term
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce term.
	 *
	 * @return the user uuid of this commerce term
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce term.
	 *
	 * @param userUuid the user uuid of this commerce term
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce term.
	 *
	 * @return the user name of this commerce term
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce term.
	 *
	 * @param userName the user name of this commerce term
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce term.
	 *
	 * @return the create date of this commerce term
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce term.
	 *
	 * @param createDate the create date of this commerce term
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce term.
	 *
	 * @return the modified date of this commerce term
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce term.
	 *
	 * @param modifiedDate the modified date of this commerce term
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this commerce term.
	 *
	 * @return the active of this commerce term
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this commerce term is active.
	 *
	 * @return <code>true</code> if this commerce term is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this commerce term is active.
	 *
	 * @param active the active of this commerce term
	 */
	public void setActive(boolean active);

	/**
	 * Returns the description of this commerce term.
	 *
	 * @return the description of this commerce term
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this commerce term.
	 *
	 * @param description the description of this commerce term
	 */
	public void setDescription(String description);

	/**
	 * Returns the display date of this commerce term.
	 *
	 * @return the display date of this commerce term
	 */
	public Date getDisplayDate();

	/**
	 * Sets the display date of this commerce term.
	 *
	 * @param displayDate the display date of this commerce term
	 */
	public void setDisplayDate(Date displayDate);

	/**
	 * Returns the expiration date of this commerce term.
	 *
	 * @return the expiration date of this commerce term
	 */
	public Date getExpirationDate();

	/**
	 * Sets the expiration date of this commerce term.
	 *
	 * @param expirationDate the expiration date of this commerce term
	 */
	public void setExpirationDate(Date expirationDate);

	/**
	 * Returns the label of this commerce term.
	 *
	 * @return the label of this commerce term
	 */
	public String getLabel();

	/**
	 * Returns the localized label of this commerce term in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized label of this commerce term
	 */
	@AutoEscape
	public String getLabel(Locale locale);

	/**
	 * Returns the localized label of this commerce term in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized label of this commerce term. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getLabel(Locale locale, boolean useDefault);

	/**
	 * Returns the localized label of this commerce term in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized label of this commerce term
	 */
	@AutoEscape
	public String getLabel(String languageId);

	/**
	 * Returns the localized label of this commerce term in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized label of this commerce term
	 */
	@AutoEscape
	public String getLabel(String languageId, boolean useDefault);

	@AutoEscape
	public String getLabelCurrentLanguageId();

	@AutoEscape
	public String getLabelCurrentValue();

	/**
	 * Returns a map of the locales and localized labels of this commerce term.
	 *
	 * @return the locales and localized labels of this commerce term
	 */
	public Map<Locale, String> getLabelMap();

	/**
	 * Sets the label of this commerce term.
	 *
	 * @param label the label of this commerce term
	 */
	public void setLabel(String label);

	/**
	 * Sets the localized label of this commerce term in the language.
	 *
	 * @param label the localized label of this commerce term
	 * @param locale the locale of the language
	 */
	public void setLabel(String label, Locale locale);

	/**
	 * Sets the localized label of this commerce term in the language, and sets the default locale.
	 *
	 * @param label the localized label of this commerce term
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setLabel(String label, Locale locale, Locale defaultLocale);

	public void setLabelCurrentLanguageId(String languageId);

	/**
	 * Sets the localized labels of this commerce term from the map of locales and localized labels.
	 *
	 * @param labelMap the locales and localized labels of this commerce term
	 */
	public void setLabelMap(Map<Locale, String> labelMap);

	/**
	 * Sets the localized labels of this commerce term from the map of locales and localized labels, and sets the default locale.
	 *
	 * @param labelMap the locales and localized labels of this commerce term
	 * @param defaultLocale the default locale
	 */
	public void setLabelMap(Map<Locale, String> labelMap, Locale defaultLocale);

	/**
	 * Returns the name of this commerce term.
	 *
	 * @return the name of this commerce term
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this commerce term.
	 *
	 * @param name the name of this commerce term
	 */
	public void setName(String name);

	/**
	 * Returns the priority of this commerce term.
	 *
	 * @return the priority of this commerce term
	 */
	public double getPriority();

	/**
	 * Sets the priority of this commerce term.
	 *
	 * @param priority the priority of this commerce term
	 */
	public void setPriority(double priority);

	/**
	 * Returns the type of this commerce term.
	 *
	 * @return the type of this commerce term
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this commerce term.
	 *
	 * @param type the type of this commerce term
	 */
	public void setType(String type);

	/**
	 * Returns the type settings of this commerce term.
	 *
	 * @return the type settings of this commerce term
	 */
	@AutoEscape
	public String getTypeSettings();

	/**
	 * Sets the type settings of this commerce term.
	 *
	 * @param typeSettings the type settings of this commerce term
	 */
	public void setTypeSettings(String typeSettings);

	/**
	 * Returns the last publish date of this commerce term.
	 *
	 * @return the last publish date of this commerce term
	 */
	public Date getLastPublishDate();

	/**
	 * Sets the last publish date of this commerce term.
	 *
	 * @param lastPublishDate the last publish date of this commerce term
	 */
	public void setLastPublishDate(Date lastPublishDate);

	/**
	 * Returns the status of this commerce term.
	 *
	 * @return the status of this commerce term
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this commerce term.
	 *
	 * @param status the status of this commerce term
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this commerce term.
	 *
	 * @return the status by user ID of this commerce term
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this commerce term.
	 *
	 * @param statusByUserId the status by user ID of this commerce term
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this commerce term.
	 *
	 * @return the status by user uuid of this commerce term
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this commerce term.
	 *
	 * @param statusByUserUuid the status by user uuid of this commerce term
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this commerce term.
	 *
	 * @return the status by user name of this commerce term
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this commerce term.
	 *
	 * @param statusByUserName the status by user name of this commerce term
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this commerce term.
	 *
	 * @return the status date of this commerce term
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this commerce term.
	 *
	 * @param statusDate the status date of this commerce term
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this commerce term is approved.
	 *
	 * @return <code>true</code> if this commerce term is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this commerce term is denied.
	 *
	 * @return <code>true</code> if this commerce term is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this commerce term is a draft.
	 *
	 * @return <code>true</code> if this commerce term is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this commerce term is expired.
	 *
	 * @return <code>true</code> if this commerce term is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this commerce term is inactive.
	 *
	 * @return <code>true</code> if this commerce term is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this commerce term is incomplete.
	 *
	 * @return <code>true</code> if this commerce term is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this commerce term is pending.
	 *
	 * @return <code>true</code> if this commerce term is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this commerce term is scheduled.
	 *
	 * @return <code>true</code> if this commerce term is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public CommerceTerm cloneWithOriginalValues();

}