/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.alloy.mvc.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TodoList service. Represents a row in the &quot;AlloyMVCSample_TodoList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.alloy.mvc.sample.model.impl.TodoListModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.alloy.mvc.sample.model.impl.TodoListImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TodoList
 * @generated
 */
@ProviderType
public interface TodoListModel
	extends AuditedModel, BaseModel<TodoList>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a todo list model instance should use the {@link TodoList} interface instead.
	 */

	/**
	 * Returns the primary key of this todo list.
	 *
	 * @return the primary key of this todo list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this todo list.
	 *
	 * @param primaryKey the primary key of this todo list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this todo list.
	 *
	 * @return the mvcc version of this todo list
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this todo list.
	 *
	 * @param mvccVersion the mvcc version of this todo list
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the todo list ID of this todo list.
	 *
	 * @return the todo list ID of this todo list
	 */
	public long getTodoListId();

	/**
	 * Sets the todo list ID of this todo list.
	 *
	 * @param todoListId the todo list ID of this todo list
	 */
	public void setTodoListId(long todoListId);

	/**
	 * Returns the company ID of this todo list.
	 *
	 * @return the company ID of this todo list
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this todo list.
	 *
	 * @param companyId the company ID of this todo list
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this todo list.
	 *
	 * @return the user ID of this todo list
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this todo list.
	 *
	 * @param userId the user ID of this todo list
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this todo list.
	 *
	 * @return the user uuid of this todo list
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this todo list.
	 *
	 * @param userUuid the user uuid of this todo list
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this todo list.
	 *
	 * @return the user name of this todo list
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this todo list.
	 *
	 * @param userName the user name of this todo list
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this todo list.
	 *
	 * @return the create date of this todo list
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this todo list.
	 *
	 * @param createDate the create date of this todo list
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this todo list.
	 *
	 * @return the modified date of this todo list
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this todo list.
	 *
	 * @param modifiedDate the modified date of this todo list
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this todo list.
	 *
	 * @return the name of this todo list
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this todo list.
	 *
	 * @param name the name of this todo list
	 */
	public void setName(String name);

}