/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CacheMissEntry service. Represents a row in the &quot;CacheMissEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.CacheMissEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.CacheMissEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CacheMissEntry
 * @generated
 */
@ProviderType
public interface CacheMissEntryModel
	extends BaseModel<CacheMissEntry>, CTModel<CacheMissEntry>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cache miss entry model instance should use the {@link CacheMissEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this cache miss entry.
	 *
	 * @return the primary key of this cache miss entry
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cache miss entry.
	 *
	 * @param primaryKey the primary key of this cache miss entry
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this cache miss entry.
	 *
	 * @return the mvcc version of this cache miss entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this cache miss entry.
	 *
	 * @param mvccVersion the mvcc version of this cache miss entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this cache miss entry.
	 *
	 * @return the ct collection ID of this cache miss entry
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this cache miss entry.
	 *
	 * @param ctCollectionId the ct collection ID of this cache miss entry
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the cache miss entry ID of this cache miss entry.
	 *
	 * @return the cache miss entry ID of this cache miss entry
	 */
	public long getCacheMissEntryId();

	/**
	 * Sets the cache miss entry ID of this cache miss entry.
	 *
	 * @param cacheMissEntryId the cache miss entry ID of this cache miss entry
	 */
	public void setCacheMissEntryId(long cacheMissEntryId);

	@Override
	public CacheMissEntry cloneWithOriginalValues();

}