create table SXPBlueprint (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	sxpBlueprintId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	configurationJSON TEXT null,
	description STRING null,
	elementInstancesJSON TEXT null,
	key_ VARCHAR(75) null,
	schemaVersion VARCHAR(75) null,
	title STRING null,
	version VARCHAR(75) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table SXPElement (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	sxpElementId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	description STRING null,
	elementDefinitionJSON TEXT null,
	hidden_ BOOLEAN,
	key_ VARCHAR(75) null,
	readOnly BOOLEAN,
	schemaVersion VARCHAR(75) null,
	title STRING null,
	type_ INTEGER,
	version VARCHAR(75) null,
	status INTEGER
);