/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.object.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.object.model.ObjectLayoutBoxRow;
import com.liferay.object.model.ObjectLayoutBoxRowModel;
import com.liferay.object.model.ObjectLayoutBoxRowSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ObjectLayoutBoxRow service. Represents a row in the &quot;ObjectLayoutBoxRow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ObjectLayoutBoxRowModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ObjectLayoutBoxRowImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see ObjectLayoutBoxRowImpl
 * @generated
 */
@JSON(strict = true)
public class ObjectLayoutBoxRowModelImpl
	extends BaseModelImpl<ObjectLayoutBoxRow>
	implements ObjectLayoutBoxRowModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a object layout box row model instance should use the <code>ObjectLayoutBoxRow</code> interface instead.
	 */
	public static final String TABLE_NAME = "ObjectLayoutBoxRow";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"objectLayoutBoxRowId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"objectLayoutBoxId", Types.BIGINT}, {"priority", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("objectLayoutBoxRowId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("objectLayoutBoxId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ObjectLayoutBoxRow (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,objectLayoutBoxRowId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,objectLayoutBoxId LONG,priority INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table ObjectLayoutBoxRow";

	public static final String ORDER_BY_JPQL =
		" ORDER BY objectLayoutBoxRow.objectLayoutBoxRowId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ObjectLayoutBoxRow.objectLayoutBoxRowId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OBJECTLAYOUTBOXROWID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ObjectLayoutBoxRow toModel(ObjectLayoutBoxRowSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ObjectLayoutBoxRow model = new ObjectLayoutBoxRowImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setObjectLayoutBoxRowId(soapModel.getObjectLayoutBoxRowId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setObjectLayoutBoxId(soapModel.getObjectLayoutBoxId());
		model.setPriority(soapModel.getPriority());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ObjectLayoutBoxRow> toModels(
		ObjectLayoutBoxRowSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ObjectLayoutBoxRow> models = new ArrayList<ObjectLayoutBoxRow>(
			soapModels.length);

		for (ObjectLayoutBoxRowSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ObjectLayoutBoxRowModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _objectLayoutBoxRowId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setObjectLayoutBoxRowId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _objectLayoutBoxRowId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ObjectLayoutBoxRow.class;
	}

	@Override
	public String getModelClassName() {
		return ObjectLayoutBoxRow.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ObjectLayoutBoxRow, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ObjectLayoutBoxRow, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ObjectLayoutBoxRow, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ObjectLayoutBoxRow)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ObjectLayoutBoxRow, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ObjectLayoutBoxRow, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ObjectLayoutBoxRow)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ObjectLayoutBoxRow, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ObjectLayoutBoxRow, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ObjectLayoutBoxRow>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ObjectLayoutBoxRow.class.getClassLoader(), ObjectLayoutBoxRow.class,
			ModelWrapper.class);

		try {
			Constructor<ObjectLayoutBoxRow> constructor =
				(Constructor<ObjectLayoutBoxRow>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ObjectLayoutBoxRow, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ObjectLayoutBoxRow, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ObjectLayoutBoxRow, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ObjectLayoutBoxRow, Object>>();
		Map<String, BiConsumer<ObjectLayoutBoxRow, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ObjectLayoutBoxRow, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", ObjectLayoutBoxRow::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<ObjectLayoutBoxRow, Long>)
				ObjectLayoutBoxRow::setMvccVersion);
		attributeGetterFunctions.put("uuid", ObjectLayoutBoxRow::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ObjectLayoutBoxRow, String>)
				ObjectLayoutBoxRow::setUuid);
		attributeGetterFunctions.put(
			"objectLayoutBoxRowId",
			ObjectLayoutBoxRow::getObjectLayoutBoxRowId);
		attributeSetterBiConsumers.put(
			"objectLayoutBoxRowId",
			(BiConsumer<ObjectLayoutBoxRow, Long>)
				ObjectLayoutBoxRow::setObjectLayoutBoxRowId);
		attributeGetterFunctions.put(
			"companyId", ObjectLayoutBoxRow::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ObjectLayoutBoxRow, Long>)
				ObjectLayoutBoxRow::setCompanyId);
		attributeGetterFunctions.put("userId", ObjectLayoutBoxRow::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ObjectLayoutBoxRow, Long>)
				ObjectLayoutBoxRow::setUserId);
		attributeGetterFunctions.put(
			"userName", ObjectLayoutBoxRow::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ObjectLayoutBoxRow, String>)
				ObjectLayoutBoxRow::setUserName);
		attributeGetterFunctions.put(
			"createDate", ObjectLayoutBoxRow::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ObjectLayoutBoxRow, Date>)
				ObjectLayoutBoxRow::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ObjectLayoutBoxRow::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ObjectLayoutBoxRow, Date>)
				ObjectLayoutBoxRow::setModifiedDate);
		attributeGetterFunctions.put(
			"objectLayoutBoxId", ObjectLayoutBoxRow::getObjectLayoutBoxId);
		attributeSetterBiConsumers.put(
			"objectLayoutBoxId",
			(BiConsumer<ObjectLayoutBoxRow, Long>)
				ObjectLayoutBoxRow::setObjectLayoutBoxId);
		attributeGetterFunctions.put(
			"priority", ObjectLayoutBoxRow::getPriority);
		attributeSetterBiConsumers.put(
			"priority",
			(BiConsumer<ObjectLayoutBoxRow, Integer>)
				ObjectLayoutBoxRow::setPriority);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getObjectLayoutBoxRowId() {
		return _objectLayoutBoxRowId;
	}

	@Override
	public void setObjectLayoutBoxRowId(long objectLayoutBoxRowId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_objectLayoutBoxRowId = objectLayoutBoxRowId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getObjectLayoutBoxId() {
		return _objectLayoutBoxId;
	}

	@Override
	public void setObjectLayoutBoxId(long objectLayoutBoxId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_objectLayoutBoxId = objectLayoutBoxId;
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_priority = priority;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ObjectLayoutBoxRow.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ObjectLayoutBoxRow.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ObjectLayoutBoxRow toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ObjectLayoutBoxRow>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ObjectLayoutBoxRowImpl objectLayoutBoxRowImpl =
			new ObjectLayoutBoxRowImpl();

		objectLayoutBoxRowImpl.setMvccVersion(getMvccVersion());
		objectLayoutBoxRowImpl.setUuid(getUuid());
		objectLayoutBoxRowImpl.setObjectLayoutBoxRowId(
			getObjectLayoutBoxRowId());
		objectLayoutBoxRowImpl.setCompanyId(getCompanyId());
		objectLayoutBoxRowImpl.setUserId(getUserId());
		objectLayoutBoxRowImpl.setUserName(getUserName());
		objectLayoutBoxRowImpl.setCreateDate(getCreateDate());
		objectLayoutBoxRowImpl.setModifiedDate(getModifiedDate());
		objectLayoutBoxRowImpl.setObjectLayoutBoxId(getObjectLayoutBoxId());
		objectLayoutBoxRowImpl.setPriority(getPriority());

		objectLayoutBoxRowImpl.resetOriginalValues();

		return objectLayoutBoxRowImpl;
	}

	@Override
	public ObjectLayoutBoxRow cloneWithOriginalValues() {
		ObjectLayoutBoxRowImpl objectLayoutBoxRowImpl =
			new ObjectLayoutBoxRowImpl();

		objectLayoutBoxRowImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		objectLayoutBoxRowImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		objectLayoutBoxRowImpl.setObjectLayoutBoxRowId(
			this.<Long>getColumnOriginalValue("objectLayoutBoxRowId"));
		objectLayoutBoxRowImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		objectLayoutBoxRowImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		objectLayoutBoxRowImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		objectLayoutBoxRowImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		objectLayoutBoxRowImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		objectLayoutBoxRowImpl.setObjectLayoutBoxId(
			this.<Long>getColumnOriginalValue("objectLayoutBoxId"));
		objectLayoutBoxRowImpl.setPriority(
			this.<Integer>getColumnOriginalValue("priority"));

		return objectLayoutBoxRowImpl;
	}

	@Override
	public int compareTo(ObjectLayoutBoxRow objectLayoutBoxRow) {
		long primaryKey = objectLayoutBoxRow.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ObjectLayoutBoxRow)) {
			return false;
		}

		ObjectLayoutBoxRow objectLayoutBoxRow = (ObjectLayoutBoxRow)object;

		long primaryKey = objectLayoutBoxRow.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ObjectLayoutBoxRow> toCacheModel() {
		ObjectLayoutBoxRowCacheModel objectLayoutBoxRowCacheModel =
			new ObjectLayoutBoxRowCacheModel();

		objectLayoutBoxRowCacheModel.mvccVersion = getMvccVersion();

		objectLayoutBoxRowCacheModel.uuid = getUuid();

		String uuid = objectLayoutBoxRowCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			objectLayoutBoxRowCacheModel.uuid = null;
		}

		objectLayoutBoxRowCacheModel.objectLayoutBoxRowId =
			getObjectLayoutBoxRowId();

		objectLayoutBoxRowCacheModel.companyId = getCompanyId();

		objectLayoutBoxRowCacheModel.userId = getUserId();

		objectLayoutBoxRowCacheModel.userName = getUserName();

		String userName = objectLayoutBoxRowCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			objectLayoutBoxRowCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			objectLayoutBoxRowCacheModel.createDate = createDate.getTime();
		}
		else {
			objectLayoutBoxRowCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			objectLayoutBoxRowCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			objectLayoutBoxRowCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		objectLayoutBoxRowCacheModel.objectLayoutBoxId = getObjectLayoutBoxId();

		objectLayoutBoxRowCacheModel.priority = getPriority();

		return objectLayoutBoxRowCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ObjectLayoutBoxRow, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ObjectLayoutBoxRow, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ObjectLayoutBoxRow, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ObjectLayoutBoxRow)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ObjectLayoutBoxRow, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ObjectLayoutBoxRow, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ObjectLayoutBoxRow, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ObjectLayoutBoxRow)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ObjectLayoutBoxRow>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private String _uuid;
	private long _objectLayoutBoxRowId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _objectLayoutBoxId;
	private int _priority;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ObjectLayoutBoxRow, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ObjectLayoutBoxRow)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"objectLayoutBoxRowId", _objectLayoutBoxRowId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("objectLayoutBoxId", _objectLayoutBoxId);
		_columnOriginalValues.put("priority", _priority);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("objectLayoutBoxRowId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("objectLayoutBoxId", 256L);

		columnBitmasks.put("priority", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ObjectLayoutBoxRow _escapedModel;

}