services:
    able-remote-app:
        container_name: t7h3-able-remote_app
        image: dragas/thttpd
        ports:
            - 9001:80
        volumes:
            - ./extensions/able-remote-app/build/static:/var/www/http
    baker-webhook:
        command: java -jar baker-webhook.jar
        container_name: t7h3-baker-webhook
        environment:
            - "LXC_EXTENSION_BAKER_WEBHOOK_SECRET=pgyP2sdYFaUreq4"
        image: liferay/jdk11
        ports:
            - 9002:8080
        volumes:
            - ./extensions/baker-webhook/build/libs:/opt/baker-webhook
        working_dir: /opt/baker-webhook
    charlie-job-runner:
        container_name: t7h3-charlie-job-runner
        image: liferay/job-runner
        volumes:
            - ./extensions/charlie-job-runner/job-runner:/mnt/liferay
    liferay:
        container_name: t7h3-liferay
        environment:
            - "LXC_EXTENSION_ABLE_REMOTE_APP_URL=http://localhost:9001"
            - "LXC_EXTENSION_BAKER_WEBHOOK_SECRET=pgyP2sdYFaUreq4"
            - "LXC_EXTENSION_BAKER_WEBHOOK_URL=http://localhost:9002"
        image: liferay/dxp:7.4.13-u20
        ports:
            - 8080:8080
        volumes:
            - ./extensions:/opt/liferay/lxc/extensions
            - ./site-initializers:/opt/liferay/lxc/site-initializers