/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.custom.elements.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CustomElementsSource service. Represents a row in the &quot;CustomElementsSource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.custom.elements.model.impl.CustomElementsSourceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.custom.elements.model.impl.CustomElementsSourceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomElementsSource
 * @generated
 */
@ProviderType
public interface CustomElementsSourceModel
	extends BaseModel<CustomElementsSource>, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom elements source model instance should use the {@link CustomElementsSource} interface instead.
	 */

	/**
	 * Returns the primary key of this custom elements source.
	 *
	 * @return the primary key of this custom elements source
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom elements source.
	 *
	 * @param primaryKey the primary key of this custom elements source
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this custom elements source.
	 *
	 * @return the mvcc version of this custom elements source
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this custom elements source.
	 *
	 * @param mvccVersion the mvcc version of this custom elements source
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this custom elements source.
	 *
	 * @return the uuid of this custom elements source
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this custom elements source.
	 *
	 * @param uuid the uuid of this custom elements source
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the custom elements source ID of this custom elements source.
	 *
	 * @return the custom elements source ID of this custom elements source
	 */
	public long getCustomElementsSourceId();

	/**
	 * Sets the custom elements source ID of this custom elements source.
	 *
	 * @param customElementsSourceId the custom elements source ID of this custom elements source
	 */
	public void setCustomElementsSourceId(long customElementsSourceId);

	/**
	 * Returns the company ID of this custom elements source.
	 *
	 * @return the company ID of this custom elements source
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this custom elements source.
	 *
	 * @param companyId the company ID of this custom elements source
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this custom elements source.
	 *
	 * @return the user ID of this custom elements source
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this custom elements source.
	 *
	 * @param userId the user ID of this custom elements source
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom elements source.
	 *
	 * @return the user uuid of this custom elements source
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this custom elements source.
	 *
	 * @param userUuid the user uuid of this custom elements source
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this custom elements source.
	 *
	 * @return the user name of this custom elements source
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this custom elements source.
	 *
	 * @param userName the user name of this custom elements source
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this custom elements source.
	 *
	 * @return the create date of this custom elements source
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this custom elements source.
	 *
	 * @param createDate the create date of this custom elements source
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this custom elements source.
	 *
	 * @return the modified date of this custom elements source
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this custom elements source.
	 *
	 * @param modifiedDate the modified date of this custom elements source
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the html element name of this custom elements source.
	 *
	 * @return the html element name of this custom elements source
	 */
	@AutoEscape
	public String getHTMLElementName();

	/**
	 * Sets the html element name of this custom elements source.
	 *
	 * @param htmlElementName the html element name of this custom elements source
	 */
	public void setHTMLElementName(String htmlElementName);

	/**
	 * Returns the name of this custom elements source.
	 *
	 * @return the name of this custom elements source
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this custom elements source.
	 *
	 * @param name the name of this custom elements source
	 */
	public void setName(String name);

	/**
	 * Returns the urls of this custom elements source.
	 *
	 * @return the urls of this custom elements source
	 */
	@AutoEscape
	public String getURLs();

	/**
	 * Sets the urls of this custom elements source.
	 *
	 * @param urls the urls of this custom elements source
	 */
	public void setURLs(String urls);

	@Override
	public CustomElementsSource cloneWithOriginalValues();

}