/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.custom.elements.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CustomElementsPortletDescriptor service. Represents a row in the &quot;CustomElementsPortletDesc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.custom.elements.model.impl.CustomElementsPortletDescriptorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.custom.elements.model.impl.CustomElementsPortletDescriptorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomElementsPortletDescriptor
 * @generated
 */
@ProviderType
public interface CustomElementsPortletDescriptorModel
	extends BaseModel<CustomElementsPortletDescriptor>, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom elements portlet descriptor model instance should use the {@link CustomElementsPortletDescriptor} interface instead.
	 */

	/**
	 * Returns the primary key of this custom elements portlet descriptor.
	 *
	 * @return the primary key of this custom elements portlet descriptor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom elements portlet descriptor.
	 *
	 * @param primaryKey the primary key of this custom elements portlet descriptor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this custom elements portlet descriptor.
	 *
	 * @return the mvcc version of this custom elements portlet descriptor
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this custom elements portlet descriptor.
	 *
	 * @param mvccVersion the mvcc version of this custom elements portlet descriptor
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this custom elements portlet descriptor.
	 *
	 * @return the uuid of this custom elements portlet descriptor
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this custom elements portlet descriptor.
	 *
	 * @param uuid the uuid of this custom elements portlet descriptor
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the custom elements portlet descriptor ID of this custom elements portlet descriptor.
	 *
	 * @return the custom elements portlet descriptor ID of this custom elements portlet descriptor
	 */
	public long getCustomElementsPortletDescriptorId();

	/**
	 * Sets the custom elements portlet descriptor ID of this custom elements portlet descriptor.
	 *
	 * @param customElementsPortletDescriptorId the custom elements portlet descriptor ID of this custom elements portlet descriptor
	 */
	public void setCustomElementsPortletDescriptorId(
		long customElementsPortletDescriptorId);

	/**
	 * Returns the company ID of this custom elements portlet descriptor.
	 *
	 * @return the company ID of this custom elements portlet descriptor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this custom elements portlet descriptor.
	 *
	 * @param companyId the company ID of this custom elements portlet descriptor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this custom elements portlet descriptor.
	 *
	 * @return the user ID of this custom elements portlet descriptor
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this custom elements portlet descriptor.
	 *
	 * @param userId the user ID of this custom elements portlet descriptor
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom elements portlet descriptor.
	 *
	 * @return the user uuid of this custom elements portlet descriptor
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this custom elements portlet descriptor.
	 *
	 * @param userUuid the user uuid of this custom elements portlet descriptor
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this custom elements portlet descriptor.
	 *
	 * @return the user name of this custom elements portlet descriptor
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this custom elements portlet descriptor.
	 *
	 * @param userName the user name of this custom elements portlet descriptor
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this custom elements portlet descriptor.
	 *
	 * @return the create date of this custom elements portlet descriptor
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this custom elements portlet descriptor.
	 *
	 * @param createDate the create date of this custom elements portlet descriptor
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this custom elements portlet descriptor.
	 *
	 * @return the modified date of this custom elements portlet descriptor
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this custom elements portlet descriptor.
	 *
	 * @param modifiedDate the modified date of this custom elements portlet descriptor
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the css ur ls of this custom elements portlet descriptor.
	 *
	 * @return the css ur ls of this custom elements portlet descriptor
	 */
	@AutoEscape
	public String getCSSURLs();

	/**
	 * Sets the css ur ls of this custom elements portlet descriptor.
	 *
	 * @param cssURLs the css ur ls of this custom elements portlet descriptor
	 */
	public void setCSSURLs(String cssURLs);

	/**
	 * Returns the html element name of this custom elements portlet descriptor.
	 *
	 * @return the html element name of this custom elements portlet descriptor
	 */
	@AutoEscape
	public String getHTMLElementName();

	/**
	 * Sets the html element name of this custom elements portlet descriptor.
	 *
	 * @param htmlElementName the html element name of this custom elements portlet descriptor
	 */
	public void setHTMLElementName(String htmlElementName);

	/**
	 * Returns the instanceable of this custom elements portlet descriptor.
	 *
	 * @return the instanceable of this custom elements portlet descriptor
	 */
	public boolean getInstanceable();

	/**
	 * Returns <code>true</code> if this custom elements portlet descriptor is instanceable.
	 *
	 * @return <code>true</code> if this custom elements portlet descriptor is instanceable; <code>false</code> otherwise
	 */
	public boolean isInstanceable();

	/**
	 * Sets whether this custom elements portlet descriptor is instanceable.
	 *
	 * @param instanceable the instanceable of this custom elements portlet descriptor
	 */
	public void setInstanceable(boolean instanceable);

	/**
	 * Returns the name of this custom elements portlet descriptor.
	 *
	 * @return the name of this custom elements portlet descriptor
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this custom elements portlet descriptor.
	 *
	 * @param name the name of this custom elements portlet descriptor
	 */
	public void setName(String name);

	/**
	 * Returns the properties of this custom elements portlet descriptor.
	 *
	 * @return the properties of this custom elements portlet descriptor
	 */
	@AutoEscape
	public String getProperties();

	/**
	 * Sets the properties of this custom elements portlet descriptor.
	 *
	 * @param properties the properties of this custom elements portlet descriptor
	 */
	public void setProperties(String properties);

	@Override
	public CustomElementsPortletDescriptor cloneWithOriginalValues();

}