/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.order.rule.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommerceOrderRuleEntry service. Represents a row in the &quot;CommerceOrderRuleEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.order.rule.model.impl.CommerceOrderRuleEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.order.rule.model.impl.CommerceOrderRuleEntryImpl</code>.
 * </p>
 *
 * @author Luca Pellizzon
 * @see CommerceOrderRuleEntry
 * @generated
 */
@ProviderType
public interface CommerceOrderRuleEntryModel
	extends AuditedModel, BaseModel<CommerceOrderRuleEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce order rule entry model instance should use the {@link CommerceOrderRuleEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce order rule entry.
	 *
	 * @return the primary key of this commerce order rule entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce order rule entry.
	 *
	 * @param primaryKey the primary key of this commerce order rule entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the external reference code of this commerce order rule entry.
	 *
	 * @return the external reference code of this commerce order rule entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this commerce order rule entry.
	 *
	 * @param externalReferenceCode the external reference code of this commerce order rule entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the commerce order rule entry ID of this commerce order rule entry.
	 *
	 * @return the commerce order rule entry ID of this commerce order rule entry
	 */
	public long getCommerceOrderRuleEntryId();

	/**
	 * Sets the commerce order rule entry ID of this commerce order rule entry.
	 *
	 * @param commerceOrderRuleEntryId the commerce order rule entry ID of this commerce order rule entry
	 */
	public void setCommerceOrderRuleEntryId(long commerceOrderRuleEntryId);

	/**
	 * Returns the company ID of this commerce order rule entry.
	 *
	 * @return the company ID of this commerce order rule entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce order rule entry.
	 *
	 * @param companyId the company ID of this commerce order rule entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce order rule entry.
	 *
	 * @return the user ID of this commerce order rule entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce order rule entry.
	 *
	 * @param userId the user ID of this commerce order rule entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce order rule entry.
	 *
	 * @return the user uuid of this commerce order rule entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce order rule entry.
	 *
	 * @param userUuid the user uuid of this commerce order rule entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce order rule entry.
	 *
	 * @return the user name of this commerce order rule entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce order rule entry.
	 *
	 * @param userName the user name of this commerce order rule entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce order rule entry.
	 *
	 * @return the create date of this commerce order rule entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce order rule entry.
	 *
	 * @param createDate the create date of this commerce order rule entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce order rule entry.
	 *
	 * @return the modified date of this commerce order rule entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce order rule entry.
	 *
	 * @param modifiedDate the modified date of this commerce order rule entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this commerce order rule entry.
	 *
	 * @return the active of this commerce order rule entry
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this commerce order rule entry is active.
	 *
	 * @return <code>true</code> if this commerce order rule entry is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this commerce order rule entry is active.
	 *
	 * @param active the active of this commerce order rule entry
	 */
	public void setActive(boolean active);

	/**
	 * Returns the description of this commerce order rule entry.
	 *
	 * @return the description of this commerce order rule entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this commerce order rule entry.
	 *
	 * @param description the description of this commerce order rule entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the name of this commerce order rule entry.
	 *
	 * @return the name of this commerce order rule entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this commerce order rule entry.
	 *
	 * @param name the name of this commerce order rule entry
	 */
	public void setName(String name);

	/**
	 * Returns the priority of this commerce order rule entry.
	 *
	 * @return the priority of this commerce order rule entry
	 */
	public int getPriority();

	/**
	 * Sets the priority of this commerce order rule entry.
	 *
	 * @param priority the priority of this commerce order rule entry
	 */
	public void setPriority(int priority);

	/**
	 * Returns the type of this commerce order rule entry.
	 *
	 * @return the type of this commerce order rule entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this commerce order rule entry.
	 *
	 * @param type the type of this commerce order rule entry
	 */
	public void setType(String type);

	/**
	 * Returns the type settings of this commerce order rule entry.
	 *
	 * @return the type settings of this commerce order rule entry
	 */
	@AutoEscape
	public String getTypeSettings();

	/**
	 * Sets the type settings of this commerce order rule entry.
	 *
	 * @param typeSettings the type settings of this commerce order rule entry
	 */
	public void setTypeSettings(String typeSettings);

	@Override
	public CommerceOrderRuleEntry cloneWithOriginalValues();

}